# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.mockito:mockito-core"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "maven"
    directory: "docker"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "docker"
    schedule:
      interval: "weekly"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
